apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://ui:80/;
        }
        location /api/ {
            proxy_pass http://api:8080/;
        }
        location /jenkins/ {
            proxy_pass http://jenkins:8080/;
        }
    }