apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels: 
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: nboaram/ui:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        volumeMounts:
        - name: ui-configs
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: ui-configs
        configMap:
          name: ui-config